image: docker:latest  # Docker CLI available here

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: youni8/flask-app

stages:
  - build
  - test
  - push

before_script:
  - apk add --no-cache py3-pip  # install pip since docker image is Alpine-based minimal
  - pip install --upgrade pip
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  tags:
    - docker
  retry: 2

test:
  stage: test
  script:
    - docker run --rm $IMAGE_NAME:latest pytest tests/
  needs:
    - build
  tags:
    - docker

push:
  stage: push
  script:
    - docker push $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  needs:
    - test
  only:
    - main
    - master
  tags:
    - docker
