stages:
  - build
  - test

variables:
  IMAGE_NAME: flask-ci-app

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME .
  tags:
    - docker

test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - pytest tests/
  tags:
    - docker
