variables:
  IMAGE_NAME: youni8/flask-app
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build
  - push

test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
  tags:
    - docker

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  tags:
    - docker
  retry: 2
  needs:
    - test

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main
    - master
  tags:
    - docker
  needs:
    - build
