stages:
  - build
  - test
  - push

variables:
  IMAGE_NAME: yourdockerhubusername/yourflaskapp
  DOCKER_TLS_CERTDIR: ""  # Disable TLS for DinD (safe in CI sandbox only)

services:
  - name: docker:dind
    alias: docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - pip install --upgrade pip

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip

build_image:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  tags:
    - docker

test:
  stage: test
  script:
    - docker run --rm $IMAGE_NAME:latest pytest tests/
  needs:
    - build_image
  tags:
    - docker

push_image:
  stage: push
  script:
    - docker push $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  needs:
    - test
  only:
    - main
    - master
  tags:
    - docker
