stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""  # Required for Docker-in-Docker to work without TLS

services:
  - docker:dind

build:
  stage: build
  image: docker:latest
  script:
    - docker info
    - docker version
    - echo "✅ Docker works in CI!"
  tags:
    - docker
