image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""          # disables TLS, needed for DinD
  IMAGE_NAME: youni8/flask-app    # replace with your Docker Hub repo

stages:
  - build
  - push

before_script:
  # Docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CI_COMMIT_SHORT_SHA

push:
  stage: push
  script:
    - docker push $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main
    - master
