stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    alias: docker

build:
  stage: build
  image: docker:latest
  script:
    - docker info
    - docker version
    - echo "Docker works in CI!"
  tags:
    - docker
