variables:
  IMAGE_NAME: youni8/flask-app
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build_and_push

test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
  tags:
    - docker

build_and_push:
  stage: build_and_push
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache py3-pip
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main
    - master
  tags:
    - docker
  needs:
    - test
